// src/pages/LandingPage.js
import React from 'react';
import { Box, Typography, Button, Container, Grid, Card, CardContent } from '@mui/material';
import { Link } from 'react-router-dom';

const LandingPage = () => {
  return (
      <Box sx={{ minHeight: '100vh', backgroundColor: '#f5f5f5', padding: '2rem 0' }}>
        {/* Main Content Container */}
        <Container maxWidth="lg">
          <Box
              sx={{
                textAlign: 'center',
                marginBottom: '3rem',
                padding: '2rem',
                backgroundColor: '#3f51b5',
                color: 'white',
                borderRadius: 2,
                boxShadow: 3,
              }}
          >
            <Typography variant="h3" sx={{ fontWeight: 600, marginBottom: '1rem', font: 'inherit' }}>
              Welcome to DocuThinker
            </Typography>
            <Typography variant="h6" sx={{ marginBottom: '2rem', font: 'inherit' }}>
              Your AI-powered solution for document summarization and analysis.
              <br />
              Upload your documents and get insights in seconds!
            </Typography>
            <Button
                component={Link}
                to="/how-to-use"
                variant="contained"
                sx={{
                  backgroundColor: '#ff9800',
                  color: 'white',
                  padding: '0.75rem 1.5rem',
                  fontSize: '1rem',
                  fontWeight: 600,
                  font: 'inherit',
                  '&:hover': {
                    backgroundColor: '#e68900',
                  },
                }}
            >
              How to Use
            </Button>
          </Box>

          {/* Features Section */}
          <Grid container spacing={4} sx={{ marginTop: '2rem' }}>
            <Grid item xs={12} md={4}>
              <Card sx={{ boxShadow: 3, borderRadius: 2, height: '100%', backgroundColor: '#fff' }}>
                <CardContent>
                  <Typography variant="h5" sx={{ fontWeight: 600, marginBottom: '1rem', color: '#3f51b5', font: 'inherit' }}>
                    Upload Documents
                  </Typography>
                  <Typography variant="body1" sx={{ marginBottom: '1rem', font: 'inherit' }}>
                    Easily upload your documents to get a summary and key insights generated by our AI.
                  </Typography>
                  <Button
                      component={Link}
                      to="/upload"
                      variant="contained"
                      sx={{
                        backgroundColor: '#3f51b5',
                        color: 'white',
                        font: 'inherit',
                        '&:hover': {
                          backgroundColor: '#333f91',
                        },
                      }}
                  >
                    Upload Document
                  </Button>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} md={4}>
              <Card sx={{ boxShadow: 3, borderRadius: 2, height: '100%', backgroundColor: '#fff' }}>
                <CardContent>
                  <Typography variant="h5" sx={{ fontWeight: 600, marginBottom: '1rem', color: '#3f51b5', font: 'inherit' }}>
                    Generate Insights
                  </Typography>
                  <Typography variant="body1" sx={{ marginBottom: '1rem', font: 'inherit' }}>
                    Get key ideas and discussion points extracted from your documents effortlessly.
                  </Typography>
                  <Button
                      component={Link}
                      to="/insights"
                      variant="contained"
                      sx={{
                        backgroundColor: '#3f51b5',
                        color: 'white',
                        font: 'inherit',
                        '&:hover': {
                          backgroundColor: '#333f91',
                        },
                      }}
                  >
                    View Insights
                  </Button>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} md={4}>
              <Card sx={{ boxShadow: 3, borderRadius: 2, height: '100%', backgroundColor: '#fff' }}>
                <CardContent>
                  <Typography variant="h5" sx={{ fontWeight: 600, marginBottom: '1rem', color: '#3f51b5', font: 'inherit' }}>
                    Chat with AI
                  </Typography>
                  <Typography variant="body1" sx={{ marginBottom: '1rem', font: 'inherit' }}>
                    Engage in conversation with our AI to get clarifications and insights about your documents.
                  </Typography>
                  <Button
                      component={Link}
                      to="/chat"
                      variant="contained"
                      sx={{
                        backgroundColor: '#3f51b5',
                        color: 'white',
                        font: 'inherit',
                        '&:hover': {
                          backgroundColor: '#333f91',
                        },
                      }}
                  >
                    Chat Now
                  </Button>
                </CardContent>
              </Card>
            </Grid>
          </Grid>

          {/* Additional Information Section */}
          <Box sx={{ marginTop: '4rem', padding: '2rem', textAlign: 'center', backgroundColor: '#fff', borderRadius: 2, boxShadow: 3 }}>
            <Typography variant="h5" sx={{ marginBottom: '1rem', fontWeight: 600, color: '#3f51b5', font: 'inherit' }}>
              Why Choose DocuThinker?
            </Typography>
            <Typography variant="body1" sx={{ maxWidth: '800px', margin: '0 auto', font: 'inherit' }}>
              Our platform is designed to simplify document analysis, provide valuable insights, and enhance productivity. Experience the future of document management with AI-powered features.
            </Typography>
          </Box>

          <Box sx={{ marginTop: '4rem', padding: '2rem', textAlign: 'center', backgroundColor: '#fff', borderRadius: 2, boxShadow: 3 }}>
            <Typography variant="h5" sx={{ marginBottom: '1rem', fontWeight: 600, color: '#3f51b5', font: 'inherit' }}>
              Learn More
            </Typography>
            <Typography variant="body1" sx={{ maxWidth: '800px', margin: '0 auto', font: 'inherit' }}>
              Visit our documentation to explore the features, functionalities, and how to get started with DocuThinker.
            </Typography>
            <Button
                href="https://github.com/hoangsonww/DocuThinker"
                target="_blank"
                variant="contained"
                sx={{
                  backgroundColor: '#3f51b5',
                  color: 'white',
                  padding: '0.75rem 1.5rem',
                  fontSize: '1rem',
                  fontWeight: 600,
                  marginTop: '1rem',
                  font: 'inherit',
                  '&:hover': {
                    backgroundColor: '#333f91',
                  },
                }}
            >
              Documentation
            </Button>
          </Box>
        </Container>
      </Box>
  );
};

export default LandingPage;
