import React from 'react';
import { Box, Typography, Button, Container, Grid, Card, CardContent } from '@mui/material';
import { Link } from 'react-router-dom';

const LandingPage = ({ theme }) => {
  const isDarkMode = theme === 'dark';

  return (
      <Box
          sx={{
            minHeight: '100vh',
            backgroundColor: isDarkMode ? '#1e1e1e' : '#f5f5f5',
            padding: '2rem 0',
            transition: 'background-color 0.3s ease',
          }}
      >
        {/* Main Content Container */}
        <Container maxWidth="lg">
          <Box
              sx={{
                textAlign: 'center',
                marginBottom: '3rem',
                padding: '2rem',
                backgroundColor: isDarkMode ? '#333' : '#f57c00',
                color: 'white',
                borderRadius: 2,
                boxShadow: 3,
                transition: 'background-color 0.3s ease',
              }}
          >
            <Typography variant="h3" sx={{ marginBottom: '1rem', font: 'inherit', fontSize: '34px', fontWeight: 600 }}>
              Welcome to DocuThinker
            </Typography>
            <Typography variant="h6" sx={{ marginBottom: '2rem', font: 'inherit', color: 'white' }}>
              Your AI-powered solution for document summarization and analysis.
              <br />
              Upload your documents and get insights in seconds!
            </Typography>
            <Button
                component={Link}
                to="/how-to-use"
                variant="contained"
                sx={{
                  backgroundColor: '#f57c00',
                  color: 'white',
                  padding: '0.75rem 1.5rem',
                  fontSize: '1rem',
                  fontWeight: 600,
                  font: 'inherit',
                  '&:hover': {
                    backgroundColor: '#ee8d00',
                  },
                }}
            >
              How to Use
            </Button>
          </Box>

          {/* Features Section */}
          <Grid container spacing={4} sx={{ marginTop: '2rem' }}>
            <Grid item xs={12} md={4}>
              <Card
                  sx={{
                    boxShadow: 3,
                    borderRadius: 2,
                    height: '100%',
                    backgroundColor: isDarkMode ? '#333' : '#fff',
                    transition: 'background-color 0.3s ease',
                  }}
              >
                <CardContent>
                  <Typography
                      variant="h5"
                      sx={{
                        marginBottom: '1rem',
                        color: isDarkMode ? '#f57c00' : '#f57c00',
                        font: 'inherit',
                        fontWeight: 600,
                        fontSize: '1.5rem',
                      }}
                  >
                    Upload Documents
                  </Typography>
                  <Typography variant="body1" sx={{ marginBottom: '1rem', font: 'inherit', color: isDarkMode ? 'white' : 'black' }}>
                    Easily upload your documents to get a summary and key insights generated by our AI.
                  </Typography>
                  <Button
                      component={Link}
                      to="/home"
                      variant="contained"
                      sx={{
                        backgroundColor: '#f57c00',
                        color: 'white',
                        font: 'inherit',
                        '&:hover': {
                          backgroundColor: '#e68900',
                        },
                      }}
                  >
                    Upload Document
                  </Button>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} md={4}>
              <Card
                  sx={{
                    boxShadow: 3,
                    borderRadius: 2,
                    height: '100%',
                    backgroundColor: isDarkMode ? '#333' : '#fff',
                    transition: 'background-color 0.3s ease',
                  }}
              >
                <CardContent>
                  <Typography
                      variant="h5"
                      sx={{
                        marginBottom: '1rem',
                        color: '#f57c00',
                        font: 'inherit',
                        fontWeight: 600,
                        fontSize: '1.5rem',
                      }}
                  >
                    Generate Insights
                  </Typography>
                  <Typography variant="body1" sx={{ marginBottom: '1rem', font: 'inherit', color: isDarkMode ? 'white' : 'black' }}>
                    Get key ideas and discussion points extracted from your documents effortlessly.
                  </Typography>
                  <Button
                      component={Link}
                      to="/home"
                      variant="contained"
                      sx={{
                        backgroundColor: '#f57c00',
                        color: 'white',
                        font: 'inherit',
                        '&:hover': {
                          backgroundColor: '#e68900',
                        },
                      }}
                  >
                    Get Started
                  </Button>
                </CardContent>
              </Card>
            </Grid>

            <Grid item xs={12} md={4}>
              <Card
                  sx={{
                    boxShadow: 3,
                    borderRadius: 2,
                    height: '100%',
                    backgroundColor: isDarkMode ? '#333' : '#fff',
                    transition: 'background-color 0.3s ease',
                  }}
              >
                <CardContent>
                  <Typography
                      variant="h5"
                      sx={{
                        marginBottom: '1rem',
                        color: '#f57c00',
                        font: 'inherit',
                        fontWeight: 600,
                        fontSize: '1.5rem',
                      }}
                  >
                    Chat with AI
                  </Typography>
                  <Typography variant="body1" sx={{ marginBottom: '1rem', font: 'inherit', color: isDarkMode ? 'white' : 'black' }}>
                    Engage in conversation with our AI to get clarifications and insights about your documents.
                  </Typography>
                  <Button
                      component={Link}
                      to="/"
                      variant="contained"
                      sx={{
                        backgroundColor: '#f57c00',
                        color: 'white',
                        font: 'inherit',
                        '&:hover': {
                          backgroundColor: '#e68900',
                        },
                      }}
                  >
                    Chat Now
                  </Button>
                </CardContent>
              </Card>
            </Grid>
          </Grid>

          {/* Additional Information Section */}
          <Box
              sx={{
                marginTop: '4rem',
                padding: '2rem',
                textAlign: 'center',
                backgroundColor: isDarkMode ? '#333' : '#fff',
                borderRadius: 2,
                boxShadow: 3,
                transition: 'background-color 0.3s ease',
              }}
          >
            <Typography
                variant="h5"
                sx={{
                  marginBottom: '1rem',
                  color: '#f57c00',
                  font: 'inherit',
                  fontWeight: 600,
                  fontSize: '1.5rem',
                }}
            >
              Why Choose DocuThinker?
            </Typography>
            <Typography variant="body1" sx={{ maxWidth: '800px', margin: '0 auto', font: 'inherit', color: isDarkMode ? 'white' : 'black' }}>
              Our platform is designed to simplify document analysis, provide valuable insights, and enhance productivity.
              Experience the future of document management with AI-powered features.
            </Typography>
          </Box>

          <Box
              sx={{
                marginTop: '4rem',
                padding: '2rem',
                textAlign: 'center',
                backgroundColor: isDarkMode ? '#333' : '#fff',
                borderRadius: 2,
                boxShadow: 3,
                transition: 'background-color 0.3s ease',
              }}
          >
            <Typography
                variant="h5"
                sx={{
                  marginBottom: '1rem',
                  color: '#f57c00',
                  font: 'inherit',
                  fontWeight: 600,
                  fontSize: '1.5rem',
                }}
            >
              Learn More
            </Typography>
            <Typography variant="body1" sx={{ maxWidth: '800px', margin: '0 auto', font: 'inherit', color: isDarkMode ? 'white' : 'black' }}>
              Visit our documentation to explore the features, functionalities, and how to get started with DocuThinker.
            </Typography>
            <Button
                href="https://github.com/hoangsonww/DocuThinker-AI-App"
                target="_blank"
                variant="contained"
                sx={{
                  backgroundColor: '#f57c00',
                  color: 'white',
                  padding: '0.75rem 1.5rem',
                  fontSize: '1rem',
                  fontWeight: 600,
                  marginTop: '1rem',
                  font: 'inherit',
                  '&:hover': {
                    backgroundColor: '#e68900',
                  },
                }}
            >
              Documentation
            </Button>
          </Box>
        </Container>
      </Box>
  );
};

export default LandingPage;
